export const    GET_ALL_MATERIALS_REQUEST = 'GET_ALL_MATERIALS_REQUEST';
export const    GET_ALL_MATERIALS_SUCCESS = 'GET_ALL_MATERIALS_SUCCESS';
export const    GET_ALL_MATERIALS_FAILURE = 'GET_ALL_MATERIALS_FAILURE';

export const    GET_MATERIAL_REQUEST = 'GET_MATERIAL_REQUEST';
export const    GET_MATERIAL_SUCCESS = 'GET_MATERIAL_SUCCESS';
export const    GET_MATERIAL_FAILURE = 'GET_MATERIAL_FAILURE';

export const    CREATE_MATERIAL_REQUEST = 'CREATE_MATERIAL_REQUEST';
export const    CREATE_MATERIAL_SUCCESS = 'CREATE_MATERIAL_SUCCESS';
export const    CREATE_MATERIAL_FAILURE = 'CREATE_MATERIAL_FAILURE';

export const    UPDATE_MATERIAL_REQUEST = 'UPDATE_MATERIAL_REQUEST';
export const    UPDATE_MATERIAL_SUCCESS = 'UPDATE_MATERIAL_SUCCESS';
export const    UPDATE_MATERIAL_FAILURE = 'UPDATE_MATERIAL_FAILURE';

export const    DELETE_MATERIAL_REQUEST = 'DELETE_MATERIAL_REQUEST';
export const    DELETE_MATERIAL_SUCCESS = 'DELETE_MATERIAL_SUCCESS';
export const    DELETE_MATERIAL_FAILURE = 'DELETE_MATERIAL_FAILURE';

