export const GET_ALL_CLASSES_REQUEST = 'GET_ALL_CLASSES_REQUEST';
export const GET_ALL_CLASSES_SUCCESS = 'GET_ALL_CLASSES_SUCCESS';
export const GET_ALL_CLASSES_FAILURE = 'GET_ALL_CLASSES_FAILURE';

export const GET_CLASS_REQUEST = 'GET_CLASS_REQUEST';
export const GET_CLASS_SUCCESS = 'GET_CLASS_SUCCESS';
export const GET_CLASS_FAILURE = 'GET_CLASS_FAILURE';

export const CREATE_CLASS_REQUEST = 'CREATE_CLASS_REQUEST';
export const CREATE_CLASS_SUCCESS = 'CREATE_CLASS_SUCCESS';
export const CREATE_CLASS_FAILURE = 'CREATE_CLASS_FAILURE';

export const UPDATE_CLASS_REQUEST = 'UPDATE_CLASS_REQUEST';
export const UPDATE_CLASS_SUCCESS = 'UPDATE_CLASS_SUCCESS';
export const UPDATE_CLASS_FAILURE = 'UPDATE_CLASS_FAILURE';

export const DELETE_CLASS_REQUEST = 'DELETE_CLASS_REQUEST';
export const DELETE_CLASS_SUCCESS = 'DELETE_CLASS_SUCCESS';
export const DELETE_CLASS_FAILURE = 'DELETE_CLASS_FAILURE';

export const GET_CLASS_SUBJECT_REQUEST = 'GET_CLASS_SUBJECT_REQUEST';
export const GET_CLASS_SUBJECT_SUCCESS = 'GET_CLASS_SUBJECT_SUCCESS';
export const GET_CLASS_SUBJECT_FAILURE = 'GET_CLASS_SUBJECT_FAILURE';


export const CREATE_CLASS_SUBJECT_REQUEST = 'CREATE_CLASS_SUBJECT_REQUEST'; 
export const CREATE_CLASS_SUBJECT_SUCCESS = 'CREATE_CLASS_SUBJECT_SUCCESS';
export const CREATE_CLASS_SUBJECT_FAILURE = 'CREATE_CLASS_SUBJECT_FAILURE';

export const DELETE_CLASS_SUBJECT_REQUEST = 'DELETE_CLASS_SUBJECT_REQUEST';
export const DELETE_CLASS_SUBJECT_SUCCESS = 'DELETE_CLASS_SUBJECT_SUCCESS';
export const DELETE_CLASS_SUBJECT_FAILURE = 'DELETE_CLASS_SUBJECT_FAILURE';

