export const GET_DASHBOARD_DATAS_REQUEST = 'GET_DASHBOARD_DATAS_REQUEST';
export const GET_DASHBOARD_DATAS_SUCCESS = 'GET_DASHBOARD_DATAS_SUCCESS';
export const GET_DASHBOARD_DATAS_FAILURE = 'GET_DASHBOARD_DATAS_FAILURE';
