export const   GET_ALL_MEDIUMS_REQUEST = 'GET_ALL_MEDIUMS_REQUEST';
export const   GET_ALL_MEDIUMS_SUCCESS = 'GET_ALL_MEDIUMS_SUCCESS';
export const   GET_ALL_MEDIUMS_FAILURE = 'GET_ALL_MEDIUMS_FAILURE';

export const   GET_MEDIUM_REQUEST = 'GET_MEDIUM_REQUEST';
export const   GET_MEDIUM_SUCCESS = 'GET_MEDIUM_SUCCESS';
export const   GET_MEDIUM_FAILURE = 'GET_MEDIUM_FAILURE';

export const   CREATE_MEDIUM_REQUEST = 'CREATE_MEDIUM_REQUEST';
export const   CREATE_MEDIUM_SUCCESS = 'CREATE_MEDIUM_SUCCESS';
export const   CREATE_MEDIUM_FAILURE = 'CREATE_MEDIUM_FAILURE';

export const   UPDATE_MEDIUM_REQUEST = 'UPDATE_MEDIUM_REQUEST';
export const   UPDATE_MEDIUM_SUCCESS = 'UPDATE_MEDIUM_SUCCESS';
export const   UPDATE_MEDIUM_FAILURE = 'UPDATE_MEDIUM_FAILURE';

export const   DELETE_MEDIUM_REQUEST = 'DELETE_MEDIUM_REQUEST';
export const   DELETE_MEDIUM_SUCCESS = 'DELETE_MEDIUM_SUCCESS';
export const   DELETE_MEDIUM_FAILURE = 'DELETE_MEDIUM_FAILURE';
