export const GET_ALL_SUPPORTS_REQUEST = 'GET_ALL_SUPPORTS_REQUEST';
export const GET_ALL_SUPPORTS_SUCCESS = 'GET_ALL_SUPPORTS_SUCCESS';
export const GET_ALL_SUPPORTS_FAILURE = 'GET_ALL_SUPPORTS_FAILURE';

export const DELETE_SUPPORT_REQUEST = 'DELETE_SUPPORT_REQUEST';
export const DELETE_SUPPORT_SUCCESS = 'DELETE_SUPPORT_SUCCESS';
export const DELETE_SUPPORT_FAILURE = 'DELETE_SUPPORT_FAILURE';


export const SOVLE_SUPPORT_REQUEST = 'SOVLE_SUPPORT_REQUEST';
export const SOVLE_SUPPORT_SUCCESS = 'SOVLE_SUPPORT_SUCCESS';
export const SOVLE_SUPPORT_FAILURE = 'SOVLE_SUPPORT_FAILURE';