export const GET_ALL_REPORTS_REQUEST = "GET_ALL_REPORTS_REQUEST";
export const GET_ALL_REPORTS_SUCCESS = "GET_ALL_REPORTS_SUCCESS";
export const GET_ALL_REPORTS_FAILURE = "GET_ALL_REPORTS_FAILURE";

export const SOLVE_REPORT_REQUEST = "SOLVE_REPORT_REQUEST";
export const SOLVE_REPORT_SUCCESS = "SOLVE_REPORT_SUCCESS";
export const SOLVE_REPORT_FAILURE = "SOLVE_REPORT_FAILURE";

export const DELETE_REPORT_REQUEST = "DELETE_REPORT_REQUEST";
export const DELETE_REPORT_SUCCESS = "DELETE_REPORT_SUCCESS";
export const DELETE_REPORT_FAILURE = "DELETE_REPORT_FAILURE";