export const   GET_ALL_SLIDERS_REQUEST = 'GET_ALL_SLIDERS_REQUEST';
export const   GET_ALL_SLIDERS_SUCCESS = 'GET_ALL_SLIDERS_SUCCESS';
export const   GET_ALL_SLIDERS_FAILURE = 'GET_ALL_SLIDERS_FAILURE';

export const   GET_SLIDER_REQUEST = 'GET_SLIDER_REQUEST';
export const   GET_SLIDER_SUCCESS = 'GET_SLIDER_SUCCESS';
export const   GET_SLIDER_FAILURE = 'GET_SLIDER_FAILURE';

export const   CREATE_SLIDER_REQUEST = 'CREATE_SLIDER_REQUEST';
export const   CREATE_SLIDER_SUCCESS = 'CREATE_SLIDER_SUCCESS';
export const   CREATE_SLIDER_FAILURE = 'CREATE_SLIDER_FAILURE';

export const   UPDATE_SLIDER_REQUEST = 'UPDATE_SLIDER_REQUEST';
export const   UPDATE_SLIDER_SUCCESS = 'UPDATE_SLIDER_SUCCESS';
export const   UPDATE_SLIDER_FAILURE = 'UPDATE_SLIDER_FAILURE';

export const   DELETE_SLIDER_REQUEST = 'DELETE_SLIDER_REQUEST';
export const   DELETE_SLIDER_SUCCESS = 'DELETE_SLIDER_SUCCESS';
export const   DELETE_SLIDER_FAILURE = 'DELETE_SLIDER_FAILURE';