export const GET_ALL_VERSIONS_REQUEST = 'GET_ALL_VERSIONS_REQUEST';
export const GET_ALL_VERSIONS_SUCCESS = 'GET_ALL_VERSIONS_SUCCESS';
export const GET_ALL_VERSIONS_FAILURE = 'GET_ALL_VERSIONS_FAILURE';

export const GET_VERSION_REQUEST = 'GET_VERSION_REQUEST';
export const GET_VERSION_SUCCESS = 'GET_VERSION_SUCCESS';
export const GET_VERSION_FAILURE = 'GET_VERSION_FAILURE';

export const CREATE_VERSION_REQUEST = 'CREATE_VERSION_REQUEST';
export const CREATE_VERSION_SUCCESS = 'CREATE_VERSION_SUCCESS';
export const CREATE_VERSION_FAILURE = 'CREATE_VERSION_FAILURE';

export const UPDATE_VERSION_REQUEST = 'UPDATE_VERSION_REQUEST';
export const UPDATE_VERSION_SUCCESS = 'UPDATE_VERSION_SUCCESS';
export const UPDATE_VERSION_FAILURE = 'UPDATE_VERSION_FAILURE';

export const DELETE_VERSION_REQUEST = 'DELETE_VERSION_REQUEST';
export const DELETE_VERSION_SUCCESS = 'DELETE_VERSION_SUCCESS';
export const DELETE_VERSION_FAILURE = 'DELETE_VERSION_FAILURE';

