export const GET_APP_SETTINGS_REQUEST = 'GET_APP_SETTINGS_REQUEST';
export const GET_APP_SETTINGS_SUCCESS = 'GET_APP_SETTINGS_SUCCESS';
export const GET_APP_SETTINGS_FAILURE = 'GET_APP_SETTINGS_FAILURE';


export const UPDATE_APP_SETTINGS_REQUEST = 'UPDATE_APP_SETTINGS_REQUEST';
export const UPDATE_APP_SETTINGS_SUCCESS = 'UPDATE_APP_SETTINGS_SUCCESS';
export const UPDATE_APP_SETTINGS_FAILURE = 'UPDATE_APP_SETTINGS_FAILURE';


export const GET_ADS_SETTINGS_REQUEST = 'GET_ADS_SETTINGS_REQUEST';
export const GET_ADS_SETTINGS_SUCCESS = 'GET_ADS_SETTINGS_SUCCESS';
export const GET_ADS_SETTINGS_FAILURE = 'GET_ADS_SETTINGS_FAILURE';


export const UPDATE_ADS_SETTINGS_REQUEST = 'UPDATE_ADS_SETTINGS_REQUEST';
export const UPDATE_ADS_SETTINGS_SUCCESS = 'UPDATE_ADS_SETTINGS_SUCCESS';
export const UPDATE_ADS_SETTINGS_FAILURE = 'UPDATE_ADS_SETTINGS_FAILURE';